### ISSUE TITLE
I can't get the stats page to show.

### ISSUE THREAD

**Issue by cowai** [awakening-church/awakening-nginx-rtmp#3]
I get a 404 when I try to navigate to the stats page. Do I need to do anything other than determining the token? At first I thought I just had a wrong token, but if I change the token to something else, I get a 403 forbidden. So it must be correct.

**Comment by Dexus** [comment]
how you call your stats page?
if the secret is "0123456789abcdef" and the ressource is "info" the hash will be "cc796ebbdb38571361d17a9be1d184a9"

so now you have to open `/p/cc796ebbdb38571361d17a9be1d184a9/info`

if you need `stats` ressource open `/p/9c8f176f7bcf7d203791e9edd65e5a61/stats`

it work without errors. So how you call the urls?

**Comment by reid** [comment]
Hey @cowai, please reopen if you still need help with this issue. Thanks!
