### ISSUE TITLE
How to disable HLS or avconv 

### ISSUE THREAD

**Issue by hoitunl** [awakening-church/awakening-nginx-rtmp#5]
Hi,

Avconv is taking to much CPU, 
please how to disable HLS or Avconv ?

Regards,

**Comment by reid** [comment]
By nature, the conversion process will take up a considerable amount of CPU time for each conversion (bitrate) used. You can reduce the amount of avconv processes by modifying this project's nginx configuration.

We use this software on DigitalOcean's 8 CPU droplet.
